/*
 * This source file was generated by the Gradle 'init' task
 */
package modelo;

import main.java.modelo.Articulo;
import main.java.modelo.Imagen;
import main.java.modelo.Promocion;
import main.java.modelo.UnidadMedida;

public class App {
    public static void main(String[] args) {
        UnidadMedida unidad1 = UnidadMedida.builder()
            .id(1L)
            .denominacion("8 porciones")
            .build();
        
        UnidadMedida unidad2 = UnidadMedida.builder()
            .id(2L)
            .denominacion("4 porciones")
            .build();
        
        UnidadMedida unidad3 = UnidadMedida.builder()
            .id(3L)
            .denominacion("1 Litro")
            .build();
        
        Imagen imagen1 = Imagen.builder()
            .id(1L)
            .denominacion("Pizza Grande Hawaiana")
            .build();
        
        Imagen imagen2 = Imagen.builder()
            .id(2L)
            .denominacion("Pizza Grande Napolitana")
            .build();
        
        Imagen imagen3 = Imagen.builder()
            .id(3L)
            .denominacion("Pizza Grande Muzza")
            .build();

        Imagen imagen4 = Imagen.builder()
            .id(4L)
            .denominacion("Pizza Chica Hawaiana")
            .build();
        
        Imagen imagen5 = Imagen.builder()
            .id(5L)
            .denominacion("Pizza Chica Napolitana")
            .build();

        Imagen imagen6 = Imagen.builder()
            .id(6L)
            .denominacion("Pizza Chica Muzza")
            .build();
        
        Imagen imagen7 = Imagen.builder()
            .id(7L)
            .denominacion("Cerveza Andes")
            .build();

        Imagen imagen8 = Imagen.builder()
            .id(8L)
            .denominacion("Cerveza Quilmes")
            .build();
        Imagen iamahappy1 = Imagen.builder()
            .id(9L)
            .denominacion("Happy Hour")
            .build();
        Imagen iamahappy2 = Imagen.builder()
            .id(10L)
            .denominacion("Happy Hour")
            .build();
        Imagen verano1 = Imagen.builder()
            .id(11L)
            .denominacion("Verano")
            .build();
        Imagen verano2 = Imagen.builder()
            .id(12L)
            .denominacion("Verano")
            .build();
        Imagen invierno1 = Imagen.builder()
            .id(13L)
            .denominacion("Invierno")
            .build();
        Imagen invierno2 = Imagen.builder()
            .id(14L)
            .denominacion("Invierno")
            .build();
        
        Articulo articulo1 = Articulo.builder()
            .id(1L)
            .denominacion("Articulo para Pizza Grande Hawaiana")
            .precioVenta(15F)
            .precioCompra(10F)
            .stockAnual(20)
            .stockMaximo(40)
            .unidadMedida(unidad1)
            .imagen(imagen1)
            .build();
        
        Articulo articulo2 = Articulo.builder()
            .id(2L)
            .denominacion("Articulo para Pizza Chica Hawaiana")
            .precioVenta(10F)
            .precioCompra(5F)
            .stockAnual(20)
            .stockMaximo(40)
            .unidadMedida(unidad2)
            .imagen(imagen4)
            .build();
        
        Articulo articulo3 = Articulo.builder()
            .id(3L)
            .denominacion("Articulo para Pizza Grande Napolitana")
            .precioVenta(20F)
            .precioCompra(15F)
            .stockAnual(15)
            .stockMaximo(30)
            .unidadMedida(unidad1)
            .imagen(imagen2)
            .build();
        
        Articulo articulo4 = Articulo.builder()
            .id(4L)
            .denominacion("Articulo para Pizza Chica Napolitana")
            .precioVenta(15F)
            .precioCompra(10F)
            .stockAnual(15)
            .stockMaximo(30)
            .unidadMedida(unidad2)
            .imagen(imagen5)
            .build();

        Articulo articulo5 = Articulo.builder()
            .id(5L)
            .denominacion("Articulo para Pizza Grande Muzza")
            .precioVenta(25F)
            .precioCompra(20F)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad1)
            .imagen(imagen3)
            .build();

        Articulo articulo6 = Articulo.builder()
            .id(6L)
            .denominacion("Articulo para Pizza Chica Muzza")
            .precioVenta(20F)
            .precioCompra(15F)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad2)
            .imagen(imagen6)
            .build();

        Articulo articulo7 = Articulo.builder()
            .id(7L)
            .denominacion("Cerveza Andes")
            .precioVenta(20F)
            .precioCompra(15F)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad3)
            .imagen(imagen7)
            .build();
        
        Articulo articulo8 = Articulo.builder()
            .id(8L)
            .denominacion("Cerveza Quilmes")
            .precioVenta(20F)
            .precioCompra(15F)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad3)
            .imagen(imagen8)
            .build();
        
        Promocion promocion1 = Promocion.builder()
            .id(1L)
            .denominacion("Promocion Happy Hour")
            .FechaDesde("2024-9-2")
            .FechaHasta("2024-12-0")
            .HoraDesde("10:00:00")
            .HoraHasta("10:00:00")
            .descpripcionDescuento("Descuento para los articulos Hawaiana Grande, Muzza Grande y Cerveza Quilmes")
            .promoImagen(). // TODO resto del archivo xd
    }
}
