/*
 * This source file was generated by the Gradle 'init' task
 */
package modelo;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.HashSet;


public class App {
    public static void main(String[] args) {
        UnidadMedida unidad1 = UnidadMedida.builder()
            .id(1L)
            .denominacion("8 porciones")
            .build();
        
        UnidadMedida unidad2 = UnidadMedida.builder()
            .id(2L)
            .denominacion("4 porciones")
            .build();
        
        UnidadMedida unidad3 = UnidadMedida.builder()
            .id(3L)
            .denominacion("1 Litro")
            .build();
        
        Imagen imagen1 = Imagen.builder()
            .id(1L)
            .denominacion("Pizza Grande Hawaiana")
            .build();
        
        Imagen imagen2 = Imagen.builder()
            .id(2L)
            .denominacion("Pizza Grande Napolitana")
            .build();
        
        Imagen imagen3 = Imagen.builder()
            .id(3L)
            .denominacion("Pizza Grande Muzza")
            .build();

        Imagen imagen4 = Imagen.builder()
            .id(4L)
            .denominacion("Pizza Chica Hawaiana")
            .build();
        
        Imagen imagen5 = Imagen.builder()
            .id(5L)
            .denominacion("Pizza Chica Napolitana")
            .build();

        Imagen imagen6 = Imagen.builder()
            .id(6L)
            .denominacion("Pizza Chica Muzza")
            .build();
        
        Imagen imagen7 = Imagen.builder()
            .id(7L)
            .denominacion("Cerveza Andes")
            .build();

        Imagen imagen8 = Imagen.builder()
            .id(8L)
            .denominacion("Cerveza Quilmes")
            .build();
        Imagen iamahappy1 = Imagen.builder()
            .id(9L)
            .denominacion("Happy Hour")
            .build();
        Imagen iamahappy2 = Imagen.builder()
            .id(10L)
            .denominacion("Happy Hour")
            .build();
        Imagen verano1 = Imagen.builder()
            .id(11L)
            .denominacion("Verano")
            .build();
        Imagen verano2 = Imagen.builder()
            .id(12L)
            .denominacion("Verano")
            .build();
        Imagen invierno1 = Imagen.builder()
            .id(13L)
            .denominacion("Invierno")
            .build();
        Imagen invierno2 = Imagen.builder()
            .id(14L)
            .denominacion("Invierno")
            .build();
        
        Articulo articulo1 = Articulo.builder()
            .id(1L)
            .denominacion("Pizza Grande Hawaiana")
            .precioVenta(15D)
            .precioCompra(10D)
            .stockAnual(20)
            .stockMaximo(40)
            .unidadMedida(unidad1)
            .imagen(imagen1)
            .build();
        
        Articulo articulo2 = Articulo.builder()
            .id(2L)
            .denominacion("Pizza Chica Hawaiana")
            .precioVenta(10D)
            .precioCompra(5D)
            .stockAnual(20)
            .stockMaximo(40)
            .unidadMedida(unidad2)
            .imagen(imagen4)
            .build();
        
        Articulo articulo3 = Articulo.builder()
            .id(3L)
            .denominacion("Pizza Grande Napolitana")
            .precioVenta(20D)
            .precioCompra(15D)
            .stockAnual(15)
            .stockMaximo(30)
            .unidadMedida(unidad1)
            .imagen(imagen2)
            .build();
        
        Articulo articulo4 = Articulo.builder()
            .id(4L)
            .denominacion("Pizza Chica Napolitana")
            .precioVenta(15D)
            .precioCompra(10D)
            .stockAnual(15)
            .stockMaximo(30)
            .unidadMedida(unidad2)
            .imagen(imagen5)
            .build();

        Articulo articulo5 = Articulo.builder()
            .id(5L)
            .denominacion("Pizza Grande Muzza")
            .precioVenta(25D)
            .precioCompra(20D)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad1)
            .imagen(imagen3)
            .build();

        Articulo articulo6 = Articulo.builder()
            .id(6L)
            .denominacion("Pizza Chica Muzza")
            .precioVenta(20D)
            .precioCompra(15D)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad2)
            .imagen(imagen6)
            .build();

        Articulo articulo7 = Articulo.builder()
            .id(7L)
            .denominacion("Cerveza Andes")
            .precioVenta(20D)
            .precioCompra(15D)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad3)
            .imagen(imagen7)
            .build();
        
        Articulo articulo8 = Articulo.builder()
            .id(8L)
            .denominacion("Cerveza Quilmes")
            .precioVenta(20D)
            .precioCompra(15D)
            .stockAnual(20)
            .stockMaximo(30)
            .unidadMedida(unidad3)
            .imagen(imagen8)
            .build();
        
        // HashSets a utilizar en el constructor de la clase promocion
        HashSet<Imagen> imagenesPromo1 = new HashSet<>();
        imagenesPromo1.add(imagen1);
        imagenesPromo1.add(imagen3);
        imagenesPromo1.add(imagen8);
        HashSet<Articulo> articulosPromo1 = new HashSet<>();
        articulosPromo1.add(articulo1);
        articulosPromo1.add(articulo2);
        articulosPromo1.add(articulo8);
        Promocion promocion1 = Promocion.builder()
            .id(1L)
            .denominacion("Promocion Happy Hour")
            .FechaDesde(LocalDate.parse("2024-11-02"))
            .FechaHasta(LocalDate.parse("2024-11-02"))
            .HoraDesde(LocalTime.parse("16:00:00"))
            .HoraHasta(LocalTime.parse("18:00:00"))
            .descpripcionDescuento("Descuento para los articulos Hawaiana Grande, Muzza Grande y Cerveza Quilmes")
            .promoImagen(imagenesPromo1)
            .promociones(articulosPromo1)
            .build();
        
            // HashSets a utilizar en el constructor de la clase promocion
        HashSet<Imagen> imagenesPromo2 = new HashSet<>();
        imagenesPromo2.add(imagen4);
        imagenesPromo2.add(imagen4);
        imagenesPromo2.add(imagen8);
        imagenesPromo2.add(imagen7);
        HashSet<Articulo> articulosPromo2 = new HashSet<>();
        articulosPromo2.add(articulo2);
        articulosPromo2.add(articulo3);
        articulosPromo2.add(articulo8);
        articulosPromo2.add(articulo7);
            Promocion promocion2 = Promocion.builder()
            .id(2L)
            .denominacion("Promocion Verano")
            .FechaDesde(LocalDate.parse("2025-01-01"))
            .FechaHasta(LocalDate.parse("2025-04-01"))
            .HoraDesde(LocalTime.parse("10:00:00"))
            .HoraHasta(LocalTime.parse("10:00:00"))
            .descpripcionDescuento("Descuento para los articulos Hawaiana Chica, Napolitana Grande, Cerveza Quilmes y Cerveza Andes")
            .promoImagen(imagenesPromo2)
            .promociones(articulosPromo2)
            .build();

            // HashSets a utilizar en el constructor de la clase promocion
        HashSet<Imagen> imagenesPromo3 = new HashSet<>();
        imagenesPromo3.add(imagen1);
        imagenesPromo3.add(imagen6);
        imagenesPromo3.add(imagen8);
        HashSet<Articulo> articulosPromo3 = new HashSet<>();
        articulosPromo3.add(articulo1);
        articulosPromo3.add(articulo6);
        articulosPromo3.add(articulo8);
            Promocion promocion3 = Promocion.builder()
            .id(3L)
            .denominacion("Promocion Invierno")
            .FechaDesde(LocalDate.parse("2025-06-01"))
            .FechaHasta(LocalDate.parse("2025-09-01"))
            .HoraDesde(LocalTime.parse("10:00:00"))
            .HoraHasta(LocalTime.parse("10:00:00"))
            .descpripcionDescuento("Descuento para los articulos Hawaiana Grande, Muzza Chica y Cerveza Quilmes")
            .promoImagen(imagenesPromo3)
            .promociones(articulosPromo3)
            .build();
        
        System.out.println("----------Articulos-----------");
        System.out.println(articulo1.getDenominacion());
        System.out.println(articulo2.getDenominacion());
        System.out.println(articulo3.getDenominacion());
        System.out.println(articulo4.getDenominacion());
        System.out.println(articulo5.getDenominacion());
        System.out.println(articulo6.getDenominacion());
        System.out.println(articulo7.getDenominacion());
        System.out.println(articulo8.getDenominacion());
        System.out.println("----------Promociones-----------");
        System.out.println("Promocion 1:");
        System.out.println(promocion1.getDenominacion());
        System.out.println("-----Articulos en Promocion 1----");
        Double total1 = 0D;
        // Se imprime la descripcion de cada articulo y se suma su precio al total de la promocion
        for (Articulo articulo : promocion1.getPromociones()) {
            System.out.println(articulo.getDenominacion());
            total1 += articulo.getPrecioVenta();
        }
        System.out.println("Total: $" + total1);
        System.out.println("-----------------");
        System.out.println("Promocion 2:");
        System.out.println(promocion2.getDenominacion());
        System.out.println("-----Articulos en Promocion 2----");
        Double total2 = 0D;
        for (Articulo articulo : promocion2.getPromociones()) {
            System.out.println(articulo.getDenominacion());
            total2 += articulo.getPrecioVenta();
        }
        System.out.println("Total: $" + total2);
        System.out.println("-----------------");

        System.out.println("Promocion 3:");
        System.out.println(promocion3.getDenominacion());
        System.out.println("-----Articulos en Promocion 3----");
        Double total3 = 0D;
        for (Articulo articulo : promocion3.getPromociones()) {
            System.out.println(articulo.getDenominacion());
            total3 += articulo.getPrecioVenta();
        }
        System.out.println("Total: $" + total3);
        System.out.println("-----------------");

        System.out.println("Promocion de Verano:\nValida desde: " + promocion2.getFechaDesde() + " " + promocion2.getHoraDesde());
        System.out.println("Valida hasta: " + promocion2.getFechaHasta() + " " + promocion2.getHoraHasta());

        if (total1 < total2 && total1 < total3) {
            System.out.println("La promocion mas economica es la numero 1, con un precio de: $" + total1);
        } else if (total2 < total1 && total2 < total3) {
            System.out.println("La promocion mas economica es la numero 2, con un precio de: $" + total2);
        } else{
            System.out.println("La promocion mas economica es la numero 3, con un precio de: $" + total3);
        }


    }
}
